__5.1.__
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.
Вычислите, по возможности не используя программирование: (5E)-1 где Е – единичная матрица размера 5х5.

__Решение:__
Исходя из определения и свойств единичной и обратной матрицы: пусть $a = 5\cdot E$, тогда $b = (5 \cdot E)^{-1}$ такова, что $a\cdot b = E$, т.е $b = \frac{1}{5}\cdot E$

In [26]:
import numpy as np
from numpy.linalg import inv, det, matrix_rank
import scipy 
import scipy.linalg

In [2]:
Е = 5*np.identity(5)
print(inv(Е))

[[ 0.2  0.   0.   0.   0. ]
 [ 0.   0.2  0.   0.   0. ]
 [ 0.   0.   0.2  0.   0. ]
 [-0.  -0.  -0.   0.2 -0. ]
 [ 0.   0.   0.   0.   0.2]]


__5.2.__
Вычислите определитель:[[1,2,3],[4,0,6],[7,8,9]]

In [5]:
m = np.array([[1,2,3],[4,0,6],[7,8,9]]) 
det(m)

59.999999999999986

__5.3.1.__ Вычислите матрицу, обратную данной: [[1,2,3],[4,0,6],[7,8,9]]


In [7]:
m = np.array([[1,2,3],[4,0,6],[7,8,9]]) 
print(inv(m))

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


__5.3.2.__ Приведите пример матрицы 4х4, ранг которой равен 1.

Все строки представляют собой линейно зависимые

In [9]:
a = np.matrix([[1, 2, 3, 4], [2, 4, 6, 8], [3, 6, 9, 12], [10, 20, 30, 40]])
a, np.linalg.matrix_rank(a)

(matrix([[ 1,  2,  3,  4],
         [ 2,  4,  6,  8],
         [ 3,  6,  9, 12],
         [10, 20, 30, 40]]),
 1)

__5.4.__
Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)


In [11]:
a = np.array([1,5]) 
b = np.array([2,8])
np.inner(a, b)

42

__5.5.__ (1, 5, 0), (2, 8, 7) и (7, 1.5, 3) Вычислите смешанное произведение трех векторов:


In [13]:
a = np.array([1,5,0]) 
b = np.array([2,8,7])
c = np.array([7,1.5,3])
np.inner(np.cross(a,b), c)

228.5

__6.1.__ Решите линейную систему:


In [15]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

__6.2.__ Найдите псевдорешение:


In [28]:
a = np.matrix([[1, 2, -1],[3, -4, 0],[8, -5, 2],[2, 0, -5],[11, 4, -7]])
b = np.matrix([1, 7, 12, 7, 15]).T
a, b

(matrix([[ 1,  2, -1],
         [ 3, -4,  0],
         [ 8, -5,  2],
         [ 2,  0, -5],
         [11,  4, -7]]),
 matrix([[ 1],
         [ 7],
         [12],
         [ 7],
         [15]]))

In [30]:
np.linalg.lstsq(a, b,rcond=None )

(matrix([[ 1.13919353],
         [-0.90498444],
         [-0.9009803 ]]),
 matrix([[0.71523211]]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

__6.3.__ Сколько решений имеет линейная система:
Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 

In [21]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(B, 0.0001)

(2, 1)

__6.4.__ Вычислите LU-разложение матрицы:


In [27]:
A = np.array([ [1, 2, 3], [2, 16, 21], [4, 28, 73] ])
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)
print(np.dot(P.transpose(), A) - np.dot(L, U))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
